### ISSUE TITLE
Error from Mend Pet ticks

### ISSUE THREAD

**Issue by Shartus** [Geigerkind/DPSMate#207]
![wow_2018-12-10_14-36-35](https://user-images.githubusercontent.com/45761775/49735982-1520f280-fc89-11e8-913c-5f9c87a62ff4.png)
Getting the message above when channeling Mend Pet (and every tick during)

row 1734:
`DB:HealingTaken(1, nil, Player, ability.."(Periodic)", 1, 0, amount-overheal, target)`

Using latest DPSMate as of writing this.

On Kronos 3

**Comment by Shartus** [comment]
Should probably add that the message happens even if the mend pet ticks aren't causing overhealing.

**Comment by Shartus** [comment]
Not sure if there is anything else than /combatlog in 1.12
[WoWCombatLog.txt](https://github.com/Geigerkind/DPSMate/files/2673279/WoWCombatLog.txt)

**Comment by Geigerkind** [comment]
Hmm
I  mean I need the explicit line of the combat log.
I dont have an oracle that tells me which caused this error :<

**Comment by Slyvampy** [comment]
Sorry, to repeat steps its hunters ability called mend pet.

1) step one download and extract zip file DpsMate-master
2) move items of folder into /interface/AddoOns/ folder
3) load game - login and select hunter (must be level 10+)
4) name pet the same name as the character name     **THIS IS THE IMPORTANT PART**
5) have the spell mend pet already purchased from trainer and press it
6) read above error message

example if my character name was "Gigerkind" and i named my pet "Gigerkind" it would throw this error.

Combat log
-----------------------------------
Gigerkind gains Mend Pet.
Gigerkind gains 189 health from your Mend Pet.    **THIS IS THE ERROR**

Interface\AddOns\DPSMate\enUS\DPSMate_ParserENUS.lua:1743: attempt to perform arithmetic on local `amount' (a nil value)

It only happens when you name the pet the same name as the character name (this is done for PvP reasons) so when someone ingame does /target Gigerkind ii would target pet instead of person.

**Comment by Slyvampy** [comment]
Gigerkind gains 189 health from your Mend Pet.
**The above line is a tick from the spell, if you close the error dialog box, upon the next tick it will reappear.**
There are 5 ticks normally, unless you get interrupted.

Both the lines at the start and after the mend pet have finished are ignored. eg:
_Gigerkind gains Mend Pet._
and
_Mend Pet fades from Gigerkind._

**Comment by Slyvampy** [comment]
Just tried this on a warlock too, and I get the same error even though the pet is not the same name.

Chopit gains 64 health from your Health Funnel.

Chopit is my Imp's name.

**Comment by lvangh** [comment]
Here's the warlock error w/ combat log
![image](https://user-images.githubusercontent.com/19690096/50048572-c73f2c80-0084-11e9-9252-50650b356206.png)

**Comment by Seperest** [comment]
I can confirm pet name does not matter. I get the same error on Symmetry WoW server. names are not similar or the same.

**Comment by DevineLykan** [comment]
I get the same issue with my pet, or when in a group with a shaman and their healing totems. Just spams the same errors!

**Comment by Tabootitz** [comment]
get same error when others heal your pet also!! hunter or warlock pets

**Comment by Geigerkind** [comment]
Should be fixed now, thanks for the report :)

**Comment by ansis00** [comment]
Hi! I'm using latest DPSMate version and getting this error when casting Health funnel or Consume Shadows on Warlock Pet:
![image](https://user-images.githubusercontent.com/56313063/66412475-46c82e80-e9fe-11e9-8541-a3a39162ec72.png)
