### ISSUE TITLE
optimization

### ISSUE THREAD

**Issue by x003** [Geigerkind/DPSMate#6]
DPSMate has a pretty rough loadup time of 3+ seconds when tested with Warmup. Even with most other beefy addons tested i've never seen one go over 1 full second of loadup impact

![capture](https://cloud.githubusercontent.com/assets/12950645/21272427/3c62c81e-c38d-11e6-9be9-d5422ac123db.PNG)

**Comment by Geigerkind** [comment]
uhm, ya. I did a lot of mistakes when designing this addon a year ago. This caused this huge startup time. The problem is simple: The addon is creating all frames that it needs, when it is loaded. Also, these frames are very detailed etc. causing to process a lot of data.
Another huge impact have all these xml files. If I created them using lua, it would be faster.

However, a rewrite for all this would probably take me a few weeks of time of pure work. I can't really afford that anymore. 

Not to mention, this is probably the most beefy addon out there ^^

I find it very unfortunate that it turned out like that. However, when I started creating this addon I was a rookie and not nearly as experienced as I am now. 

Maybe at some point I will have enough time and patience in order to deal with this issue, but for now I can't see it.

Other than the loading time, it should have no huge impact on the gameplay. (Even though there is also way too much space to optimize)

cheers!

**Comment by Geigerkind** [comment]
I guess this is better than nothing, right :/
![capture](http://i.imgur.com/KmtbB0Z.png)

You can deactivate even more useless modules if you like to decrease the loading time more.
I will see If I can improve the individual loading of each module a little but, as I said the ground work is shit^^
